---
name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump version
        id: bump
        run: |
          ./scripts/bump_version.sh

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          release_name: '${{ steps.bump.outputs.new_tag }}'
          body: |
            Actor: ${{ github.actor }}
            ActionRunner: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Build Inventory Image
        run: |
          docker build . --tag ghcr.io/lfventura/kafka-cosmosdb-topic-ts-exporter:latest --tag ghcr.io/lfventura/kafka-cosmosdb-topic-ts-exporter:${{ steps.bump.outputs.new_tag }}
          docker push ghcr.io/lfventura/kafka-cosmosdb-topic-ts-exporter --all-tags